import { Payment } from "./columns";

export const getDataPayments = async (): Promise<Payment[]> => {
  return [
    {
      id: 1,
      name: "Alice Johnson",
      status: "active",
      amount: 1250.5,
      email: "alice.johnson@example.com",
    },
    {
      id: 2,
      name: "Bob Smith",
      status: "inactive",
      amount: 300.0,
      email: "bob.smith@example.com",
    },
    {
      id: 3,
      name: "Carol Williams",
      status: "pending",
      amount: 780.25,
      email: "carol.williams@example.com",
    },
    {
      id: 4,
      name: "David Brown",
      status: "active",
      amount: 1999.99,
      email: "david.brown@example.com",
    },
    {
      id: 5,
      name: "Eva Davis",
      status: "archived",
      amount: 50.0,
      email: "eva.davis@example.com",
    },
    {
      id: 6,
      name: "Frank Miller",
      status: "active",
      amount: 450.75,
      email: "frank.miller@example.com",
    },
    {
      id: 7,
      name: "Grace Wilson",
      status: "inactive",
      amount: 1200.0,
      email: "grace.wilson@example.com",
    },
    {
      id: 8,
      name: "Henry Moore",
      status: "pending",
      amount: 610.1,
      email: "henry.moore@example.com",
    },
    {
      id: 9,
      name: "Ivy Taylor",
      status: "active",
      amount: 950.2,
      email: "ivy.taylor@example.com",
    },
    {
      id: 10,
      name: "Jack Anderson",
      status: "archived",
      amount: 85.0,
      email: "jack.anderson@example.com",
    },
    {
      id: 11,
      name: "Karen Thomas",
      status: "inactive",
      amount: 300.0,
      email: "karen.thomas@example.com",
    },
    {
      id: 12,
      name: "Leo Jackson",
      status: "active",
      amount: 1550.0,
      email: "leo.jackson@example.com",
    },
    {
      id: 13,
      name: "Mia White",
      status: "pending",
      amount: 720.45,
      email: "mia.white@example.com",
    },
    {
      id: 14,
      name: "Noah Harris",
      status: "active",
      amount: 830.3,
      email: "noah.harris@example.com",
    },
    {
      id: 15,
      name: "Olivia Martin",
      status: "archived",
      amount: 110.0,
      email: "olivia.martin@example.com",
    },
    {
      id: 16,
      name: "Paul Thompson",
      status: "inactive",
      amount: 410.0,
      email: "paul.thompson@example.com",
    },
    {
      id: 17,
      name: "Quinn Garcia",
      status: "active",
      amount: 999.99,
      email: "quinn.garcia@example.com",
    },
    {
      id: 18,
      name: "Rachel Martinez",
      status: "pending",
      amount: 640.5,
      email: "rachel.martinez@example.com",
    },
    {
      id: 19,
      name: "Sam Robinson",
      status: "active",
      amount: 1350.75,
      email: "sam.robinson@example.com",
    },
    {
      id: 20,
      name: "Tina Clark",
      status: "archived",
      amount: 200.0,
      email: "tina.clark@example.com",
    },
    {
      id: 21,
      name: "Umar Rodriguez",
      status: "inactive",
      amount: 545.6,
      email: "umar.rodriguez@example.com",
    },
    {
      id: 22,
      name: "Vera Lewis",
      status: "active",
      amount: 775.25,
      email: "vera.lewis@example.com",
    },
    {
      id: 23,
      name: "Will Lee",
      status: "pending",
      amount: 615.0,
      email: "will.lee@example.com",
    },
    {
      id: 24,
      name: "Xena Walker",
      status: "active",
      amount: 1420.99,
      email: "xena.walker@example.com",
    },
    {
      id: 25,
      name: "Yusuf Hall",
      status: "archived",
      amount: 130.0,
      email: "yusuf.hall@example.com",
    },
    {
      id: 26,
      name: "Zara Allen",
      status: "inactive",
      amount: 295.4,
      email: "zara.allen@example.com",
    },
    {
      id: 27,
      name: "Aaron Young",
      status: "pending",
      amount: 880.8,
      email: "aaron.young@example.com",
    },
    {
      id: 28,
      name: "Bella Hernandez",
      status: "active",
      amount: 1600.0,
      email: "bella.hernandez@example.com",
    },
    {
      id: 29,
      name: "Cody King",
      status: "archived",
      amount: 95.0,
      email: "cody.king@example.com",
    },
    {
      id: 30,
      name: "Diana Wright",
      status: "active",
      amount: 1205.35,
      email: "diana.wright@example.com",
    },
  ];
};
